// AUTO-GENERATED by tools/emit_dungeon_dialogs_cs.py — DO NOT EDIT BY HAND.
// Source: client/.cache/dofus-darwin-2.68 (Npcs.d2o + NpcMessages.d2o + i18n_fr.d2i) + tools/manual_overrides.json.
// To regenerate:
//   python3 tools/build_dungeon_dialog_table.py /tmp/dungeon_dialogs.json
//   python3 tools/emit_dungeon_dialogs_cs.py /tmp/dungeon_dialogs.json
using System.Collections.Generic;

namespace Giny.World.Managers.Chat
{
    // Per-dungeon dialog metadata: which vanilla NPC template lives at the
    // entrance, and which messageId/replyIds the client's d2o whitelists for it.
    // ResumeReplyId = 0 means no vanilla Reprendre feature (dialog will only
    // show Enter + Exit). EnterReplyId = 0 means no vanilla enter reply either.
    public class OneAirDungeonResumeEntry
    {
        public long DungeonId;
        public string DungeonName;
        public long EntranceMapId;
        public long ExitMapId;
        public short NpcTemplateId;
        public string NpcName;
        public int QuestionMessageId;
        public int EnterReplyId;
        public int ResumeReplyId;
        public int ExitReplyId;
    }

    public static class OneAirDungeonResumeData
    {
        // entranceMapId -> list of dungeon entries (one per dungeon accessible from
        // that map). Several dungeons can share the same entrance map and/or the
        // same NPC template (e.g. Bibiblop handles Clos des Blops + Antre du Blop
        // Multicolore Royal). The dialog is composed by merging the replies of all
        // entries sharing the clicked NPC.
        public static readonly Dictionary<long, List<OneAirDungeonResumeEntry>> ByEntrance = new Dictionary<long, List<OneAirDungeonResumeEntry>>
        {
            { 139784L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 30L, DungeonName = "Caverne du Koulosse", EntranceMapId = 139784L, ExitMapId = 139265L, NpcTemplateId = 754, NpcName = "Gardien Koalak", QuestionMessageId = 3119, EnterReplyId = 22378, ResumeReplyId = 592911, ExitReplyId = 29601 },
            } },
            { 25693696L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 28L, DungeonName = "Canopée du Kimbo", EntranceMapId = 25693696L, ExitMapId = 25693696L, NpcTemplateId = 946, NpcName = "Chachka", QuestionMessageId = 4206, EnterReplyId = 20839, ResumeReplyId = 23436, ExitReplyId = 767192 },
            } },
            { 54159661L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 62L, DungeonName = "Donjon de la mine de Sakaï", EntranceMapId = 54159661L, ExitMapId = 54159661L, NpcTemplateId = 1363, NpcName = "Hywan Kenoby", QuestionMessageId = 8153, EnterReplyId = 313277, ResumeReplyId = 26082, ExitReplyId = 767195 },
            } },
            { 54163796L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 56L, DungeonName = "Épave du Grolandais violent", EntranceMapId = 54163796L, ExitMapId = 54165334L, NpcTemplateId = 1357, NpcName = "Fantômahawk", QuestionMessageId = 8107, EnterReplyId = 380963, ResumeReplyId = 26285, ExitReplyId = 311612 },
            } },
            { 54164293L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 60L, DungeonName = "Cavernes du Kolosso", EntranceMapId = 54164293L, ExitMapId = 54164807L, NpcTemplateId = 1393, NpcName = "Professeur Xa", QuestionMessageId = 8457, EnterReplyId = 392493, ResumeReplyId = 27021, ExitReplyId = 20473 },
            } },
            { 54176049L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 54L, DungeonName = "Serre du Royalmouth", EntranceMapId = 54176049L, ExitMapId = 54175024L, NpcTemplateId = 1285, NpcName = "Truffo", QuestionMessageId = 7685, EnterReplyId = 21039, ResumeReplyId = 380945, ExitReplyId = 24167 },
            } },
            { 55836672L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 55L, DungeonName = "Excavation du Mansot Royal", EntranceMapId = 55836672L, ExitMapId = 55836672L, NpcTemplateId = 1300, NpcName = "Waldos FieldChester Potcobble", QuestionMessageId = 7834, EnterReplyId = 29610, ResumeReplyId = 380948, ExitReplyId = 767191 },
            } },
            { 56890883L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 57L, DungeonName = "Hypogée de l'Obsidiantre", EntranceMapId = 56890883L, ExitMapId = 54170450L, NpcTemplateId = 1358, NpcName = "Lave Azza", QuestionMessageId = 8109, EnterReplyId = 380739, ResumeReplyId = 29196, ExitReplyId = 319473 },
            } },
            { 60036612L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 59L, DungeonName = "Antre du Korriandre", EntranceMapId = 60036612L, ExitMapId = 60036612L, NpcTemplateId = 1391, NpcName = "Sylvie Barbe", QuestionMessageId = 8427, EnterReplyId = 26625, ResumeReplyId = 918036, ExitReplyId = 20951 },
            } },
            { 62129672L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 61L, DungeonName = "Antichambre des Gloursons", EntranceMapId = 62129672L, ExitMapId = 54165323L, NpcTemplateId = 930, NpcName = "Docteur Nauh", QuestionMessageId = 4154, EnterReplyId = 658180, ResumeReplyId = 26994, ExitReplyId = 0 },
            } },
            { 63310595L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 46L, DungeonName = "Repaire de Skeunk", EntranceMapId = 63310595L, ExitMapId = 63310595L, NpcTemplateId = 758, NpcName = "Kakolak", QuestionMessageId = 3138, EnterReplyId = 194143, ResumeReplyId = 380745, ExitReplyId = 29564 },
            } },
            { 63964672L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 51L, DungeonName = "Laboratoire du Tynril", EntranceMapId = 63964672L, ExitMapId = 63964672L, NpcTemplateId = 943, NpcName = "Mulèze", QuestionMessageId = 4197, EnterReplyId = 29205, ResumeReplyId = 29208, ExitReplyId = 767190 },
            } },
            { 66060545L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 38L, DungeonName = "Maison du Papa Nowel", EntranceMapId = 66060545L, ExitMapId = 66060545L, NpcTemplateId = 393, NpcName = "Yova Etna", QuestionMessageId = 1640, EnterReplyId = 659017, ResumeReplyId = 29582, ExitReplyId = 29581 },
            } },
            { 66061569L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 36L, DungeonName = "Donjon de Nowel", EntranceMapId = 66061569L, ExitMapId = 66061569L, NpcTemplateId = 795, NpcName = "Hector Nowel", QuestionMessageId = 3254, EnterReplyId = 746874, ResumeReplyId = 976905, ExitReplyId = 746860 },
            } },
            { 66192641L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 37L, DungeonName = "Caverne de Nowel", EntranceMapId = 66192641L, ExitMapId = 66192641L, NpcTemplateId = 393, NpcName = "Yova Etna", QuestionMessageId = 1640, EnterReplyId = 659017, ResumeReplyId = 29589, ExitReplyId = 29581 },
            } },
            { 72221696L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 6L, DungeonName = "Antre du Dragon Cochon", EntranceMapId = 72221696L, ExitMapId = 72221696L, NpcTemplateId = 784, NpcName = "Fwoued", QuestionMessageId = 3216, EnterReplyId = 483556, ResumeReplyId = 918034, ExitReplyId = 21571 },
            } },
            { 84411397L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 116L, DungeonName = "Épreuve de Draegnerys", EntranceMapId = 84411397L, ExitMapId = 84411397L, NpcTemplateId = 4946, NpcName = "Dicton Karly", QuestionMessageId = 35586, EnterReplyId = 802697, ResumeReplyId = 803580, ExitReplyId = 802692 },
            } },
            { 84411905L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 115L, DungeonName = "Repaire du Kharnozor", EntranceMapId = 84411905L, ExitMapId = 199495682L, NpcTemplateId = 4975, NpcName = "Léo Seumeurly", QuestionMessageId = 35686, EnterReplyId = 803426, ResumeReplyId = 918264, ExitReplyId = 803421 },
            } },
            { 87032320L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 47L, DungeonName = "Donjon des Squelettes", EntranceMapId = 87032320L, ExitMapId = 82314753L, NpcTemplateId = 1163, NpcName = "Klik Klak", QuestionMessageId = 7070, EnterReplyId = 27658, ResumeReplyId = 29211, ExitReplyId = 25658 },
            } },
            { 88080387L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 45L, DungeonName = "Donjon des Scarafeuilles", EntranceMapId = 88080387L, ExitMapId = 88080899L, NpcTemplateId = 781, NpcName = "El Scarador", QuestionMessageId = 3179, EnterReplyId = 379742, ResumeReplyId = 29223, ExitReplyId = 29566 },
            } },
            { 88086786L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 21L, DungeonName = "Donjon des Forgerons", EntranceMapId = 88086786L, ExitMapId = 88086786L, NpcTemplateId = 1162, NpcName = "Pavu Papry", QuestionMessageId = 7069, EnterReplyId = 27236, ResumeReplyId = 21416, ExitReplyId = 24245 },
            } },
            { 89916416L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 41L, DungeonName = "Goulet du Rasboul", EntranceMapId = 89916416L, ExitMapId = 89916416L, NpcTemplateId = 945, NpcName = "Razbitume", QuestionMessageId = 4203, EnterReplyId = 29226, ResumeReplyId = 380923, ExitReplyId = 767132 },
            } },
            { 96338944L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 48L, DungeonName = "Donjon des Tofus", EntranceMapId = 96338944L, ExitMapId = 88082705L, NpcTemplateId = 777, NpcName = "Kourk Ingalsse", QuestionMessageId = 3174, EnterReplyId = 380787, ResumeReplyId = 21425, ExitReplyId = 25637 },
                new OneAirDungeonResumeEntry { DungeonId = 50L, DungeonName = "Tofulailler Royal", EntranceMapId = 96338944L, ExitMapId = 10231814L, NpcTemplateId = 778, NpcName = "Kazy Ingalsse", QuestionMessageId = 3176, EnterReplyId = 105658, ResumeReplyId = 365464, ExitReplyId = 365463 },
            } },
            { 96993793L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 33L, DungeonName = "Donjon des Larves", EntranceMapId = 96993793L, ExitMapId = 185862148L, NpcTemplateId = 766, NpcName = "Fidji Merline", QuestionMessageId = 3151, EnterReplyId = 29040, ResumeReplyId = 26100, ExitReplyId = 727458 },
            } },
            { 99614979L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 52L, DungeonName = "Château du Wa Wabbit", EntranceMapId = 99614979L, ExitMapId = 99614979L, NpcTemplateId = 1439, NpcName = "Powte-clef", QuestionMessageId = 8886, EnterReplyId = 361776, ResumeReplyId = 285393, ExitReplyId = 26112 },
            } },
            { 101187584L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 66L, DungeonName = "Potager d'Halouine", EntranceMapId = 101187584L, ExitMapId = 101187584L, NpcTemplateId = 1768, NpcName = "Disciple d'Asid", QuestionMessageId = 12671, EnterReplyId = 362495, ResumeReplyId = 362501, ExitReplyId = 362489 },
            } },
            { 101714451L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 44L, DungeonName = "Repaire de Sphincter Cell", EntranceMapId = 101714451L, ExitMapId = 101714451L, NpcTemplateId = 818, NpcName = "Aperirel", QuestionMessageId = 3415, EnterReplyId = 19982, ResumeReplyId = 967404, ExitReplyId = 25482 },
            } },
            { 104071939L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 138L, DungeonName = "Akadémie des Gobs", EntranceMapId = 104071939L, ExitMapId = 104071939L, NpcTemplateId = 6674, NpcName = "Gobmélia", QuestionMessageId = 50515, EnterReplyId = 936740, ResumeReplyId = 936746, ExitReplyId = 936735 },
            } },
            { 104862211L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 13L, DungeonName = "Donjon des Bworks", EntranceMapId = 104862211L, ExitMapId = 104862211L, NpcTemplateId = 775, NpcName = "Bowork", QuestionMessageId = 3172, EnterReplyId = 378733, ResumeReplyId = 28994, ExitReplyId = 24392 },
            } },
            { 106694158L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 17L, DungeonName = "Terrier du Wa Wabbit", EntranceMapId = 106694158L, ExitMapId = 68420613L, NpcTemplateId = 147, NpcName = "Gawde Wabbit", QuestionMessageId = 333, EnterReplyId = 366093, ResumeReplyId = 290079, ExitReplyId = 24345 },
            } },
            { 108793118L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 67L, DungeonName = "Transporteur de Sylargh", EntranceMapId = 108793118L, ExitMapId = 108793118L, NpcTemplateId = 2005, NpcName = "Hiroze", QuestionMessageId = 14522, EnterReplyId = 366874, ResumeReplyId = 366868, ExitReplyId = 366864 },
            } },
            { 108794630L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 70L, DungeonName = "Laboratoire de Nileza", EntranceMapId = 108794630L, ExitMapId = 108794630L, NpcTemplateId = 2004, NpcName = "André Vauld", QuestionMessageId = 14520, EnterReplyId = 366879, ResumeReplyId = 366882, ExitReplyId = 366881 },
            } },
            { 108925717L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 68L, DungeonName = "Salons privés de Klime", EntranceMapId = 108925717L, ExitMapId = 108925717L, NpcTemplateId = 2006, NpcName = "Domie Natrix", QuestionMessageId = 14524, EnterReplyId = 366866, ResumeReplyId = 366873, ExitReplyId = 366872 },
            } },
            { 108927238L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 69L, DungeonName = "Forgefroide de Missiz Frizz", EntranceMapId = 108927238L, ExitMapId = 108927238L, NpcTemplateId = 2007, NpcName = "Noo", QuestionMessageId = 14528, EnterReplyId = 392433, ResumeReplyId = 366896, ExitReplyId = 366903 },
            } },
            { 112460048L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 71L, DungeonName = "Donjon du Comte Harebourg", EntranceMapId = 112460048L, ExitMapId = 112460048L, NpcTemplateId = 2008, NpcName = "Dorléans", QuestionMessageId = 15157, EnterReplyId = 366290, ResumeReplyId = 366293, ExitReplyId = 366292 },
            } },
            { 117706767L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 73L, DungeonName = "Aquadôme de Merkator", EntranceMapId = 117706767L, ExitMapId = 117706767L, NpcTemplateId = 2196, NpcName = "Théo Dolith", QuestionMessageId = 16404, EnterReplyId = 371147, ResumeReplyId = 371091, ExitReplyId = 371123 },
            } },
            { 117965057L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 72L, DungeonName = "Théâtre de Dramak", EntranceMapId = 117965057L, ExitMapId = 117965057L, NpcTemplateId = 2175, NpcName = "Otto Rhino", QuestionMessageId = 16317, EnterReplyId = 386692, ResumeReplyId = 368885, ExitReplyId = 368893 },
            } },
            { 120063489L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 1L, DungeonName = "Cour du Bouftou Royal", EntranceMapId = 120063489L, ExitMapId = 120063489L, NpcTemplateId = 173, NpcName = "Rotabla le berger", QuestionMessageId = 646, EnterReplyId = 618691, ResumeReplyId = 759732, ExitReplyId = 22734 },
            } },
            { 121636870L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 74L, DungeonName = "Pyramide d'Ombre", EntranceMapId = 121636870L, ExitMapId = 121636870L, NpcTemplateId = 2215, NpcName = "Vhé", QuestionMessageId = 16553, EnterReplyId = 19712, ResumeReplyId = 374862, ExitReplyId = 374842 },
            } },
            { 125829633L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 75L, DungeonName = "Grotte de Kanigroula", EntranceMapId = 125829633L, ExitMapId = 125829633L, NpcTemplateId = 2314, NpcName = "Kanish", QuestionMessageId = 17316, EnterReplyId = 20722, ResumeReplyId = 425217, ExitReplyId = 425219 },
            } },
            { 129499136L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 76L, DungeonName = "Palais du roi Nidas", EntranceMapId = 129499136L, ExitMapId = 129236992L, NpcTemplateId = 2351, NpcName = "Léonard", QuestionMessageId = 17885, EnterReplyId = 21431, ResumeReplyId = 425056, ExitReplyId = 425055 },
            } },
            { 130285568L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 77L, DungeonName = "Fabrique de Malléfisk", EntranceMapId = 130285568L, ExitMapId = 129368578L, NpcTemplateId = 2353, NpcName = "Inès Karcel", QuestionMessageId = 17637, EnterReplyId = 425029, ResumeReplyId = 425093, ExitReplyId = 425040 },
            } },
            { 130547712L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 79L, DungeonName = "Galerie du Phossile", EntranceMapId = 130547712L, ExitMapId = 129238529L, NpcTemplateId = 2352, NpcName = "Dyane Phossé", QuestionMessageId = 17710, EnterReplyId = 424802, ResumeReplyId = 918261, ExitReplyId = 424751 },
            } },
            { 133171202L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 80L, DungeonName = "Volière de la Haute Truche", EntranceMapId = 133171202L, ExitMapId = 133171202L, NpcTemplateId = 2436, NpcName = "Orno Tolig", QuestionMessageId = 17976, EnterReplyId = 425866, ResumeReplyId = 425788, ExitReplyId = 425777 },
            } },
            { 136056074L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 83L, DungeonName = "Trône de la Cour Sombre", EntranceMapId = 136056074L, ExitMapId = 136056074L, NpcTemplateId = 2446, NpcName = "Chambelle", QuestionMessageId = 18289, EnterReplyId = 21904, ResumeReplyId = 456634, ExitReplyId = 456264 },
            } },
            { 136577024L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 81L, DungeonName = "Ring du Capitaine Ekarlatte", EntranceMapId = 136577024L, ExitMapId = 134221826L, NpcTemplateId = 2444, NpcName = "Guy Cheutié", QuestionMessageId = 18286, EnterReplyId = 456265, ResumeReplyId = 456002, ExitReplyId = 456001 },
            } },
            { 136839168L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 82L, DungeonName = "Cave du Toxoliath", EntranceMapId = 136839168L, ExitMapId = 135269891L, NpcTemplateId = 2445, NpcName = "Starchy Tropeur", QuestionMessageId = 18285, EnterReplyId = 456638, ResumeReplyId = 456629, ExitReplyId = 525036 },
            } },
            { 139723265L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 34L, DungeonName = "Maison Fantôme", EntranceMapId = 139723265L, ExitMapId = 139723265L, NpcTemplateId = 1387, NpcName = "Gentil Organisateur Chafer", QuestionMessageId = 8319, EnterReplyId = 20577, ResumeReplyId = 29597, ExitReplyId = 29218 },
            } },
            { 140641537L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 84L, DungeonName = "Ventre de la Baleine", EntranceMapId = 140641537L, ExitMapId = 140641537L, NpcTemplateId = 2636, NpcName = "Mathilde Oualtgniz", QuestionMessageId = 19017, EnterReplyId = 460564, ResumeReplyId = 460561, ExitReplyId = 460562 },
            } },
            { 144445702L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 87L, DungeonName = "Œil de Vortex", EntranceMapId = 144445702L, ExitMapId = 144445702L, NpcTemplateId = 2662, NpcName = "Tessie Oude", QuestionMessageId = 19539, EnterReplyId = 23352, ResumeReplyId = 477675, ExitReplyId = 477678 },
            } },
            { 144707846L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 86L, DungeonName = "Horologium de XLII", EntranceMapId = 144707846L, ExitMapId = 144707846L, NpcTemplateId = 2660, NpcName = "Gardien de l'Horologium", QuestionMessageId = 19397, EnterReplyId = 477919, ResumeReplyId = 477953, ExitReplyId = 477954 },
            } },
            { 144969990L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 85L, DungeonName = "Mégalithe de Fraktale", EntranceMapId = 144969990L, ExitMapId = 144969990L, NpcTemplateId = 2661, NpcName = "Hypéria Gritch", QuestionMessageId = 19557, EnterReplyId = 23374, ResumeReplyId = 477732, ExitReplyId = 486499 },
            } },
            { 146676736L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 88L, DungeonName = "Cache de Kankreblath", EntranceMapId = 146676736L, ExitMapId = 103549440L, NpcTemplateId = 2766, NpcName = "Cloportier", QuestionMessageId = 19697, EnterReplyId = 486214, ResumeReplyId = 486210, ExitReplyId = 486264 },
            } },
            { 147851777L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 9L, DungeonName = "Domaine Ancestral", EntranceMapId = 147851777L, ExitMapId = 147851777L, NpcTemplateId = 1619, NpcName = "Tronkny Baussope", QuestionMessageId = 11970, EnterReplyId = 386722, ResumeReplyId = 507607, ExitReplyId = 365485 },
            } },
            { 149159936L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 89L, DungeonName = "Antre de la Reine Nyée", EntranceMapId = 149159936L, ExitMapId = 147853312L, NpcTemplateId = 2845, NpcName = "Saule", QuestionMessageId = 20453, EnterReplyId = 515673, ResumeReplyId = 515694, ExitReplyId = 515656 },
            } },
            { 149422080L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 10L, DungeonName = "Clairière du Chêne Mou", EntranceMapId = 149422080L, ExitMapId = 149422080L, NpcTemplateId = 797, NpcName = "Josette Taplane", QuestionMessageId = 3271, EnterReplyId = 378709, ResumeReplyId = 510697, ExitReplyId = 483280 },
            } },
            { 153881600L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 90L, DungeonName = "Crypte de Kardorim", EntranceMapId = 153881600L, ExitMapId = 153881600L, NpcTemplateId = 2907, NpcName = "Klasmor le fossoyeur", QuestionMessageId = 20830, EnterReplyId = 546228, ResumeReplyId = 555713, ExitReplyId = 546202 },
            } },
            { 156499968L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 92L, DungeonName = "Arbre de Moon", EntranceMapId = 156499968L, ExitMapId = 156499968L, NpcTemplateId = 3007, NpcName = "Servante de Moon", QuestionMessageId = 21820, EnterReplyId = 579635, ResumeReplyId = 579301, ExitReplyId = 579311 },
            } },
            { 156499971L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 27L, DungeonName = "Village Kanniboul", EntranceMapId = 156499971L, ExitMapId = 156499971L, NpcTemplateId = 1384, NpcName = "Gentil Organisateur Kanniboul", QuestionMessageId = 8271, EnterReplyId = 20317, ResumeReplyId = 576628, ExitReplyId = 21342 },
            } },
            { 158078976L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 91L, DungeonName = "Bateau du Chouque", EntranceMapId = 158078976L, ExitMapId = 158078976L, NpcTemplateId = 3008, NpcName = "Jack Martel", QuestionMessageId = 21818, EnterReplyId = 26223, ResumeReplyId = 579661, ExitReplyId = 579658 },
            } },
            { 158334976L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 3L, DungeonName = "Bibliothèque du Maître Corbac", EntranceMapId = 158334976L, ExitMapId = 158334976L, NpcTemplateId = 774, NpcName = "Virgil", QuestionMessageId = 3166, EnterReplyId = 24607, ResumeReplyId = 23784, ExitReplyId = 766658 },
            } },
            { 160565248L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 95L, DungeonName = "Défi du Chalœil", EntranceMapId = 160565248L, ExitMapId = 160432128L, NpcTemplateId = 3099, NpcName = "Filouface", QuestionMessageId = 22696, EnterReplyId = 618242, ResumeReplyId = 617679, ExitReplyId = 618201 },
            } },
            { 160960771L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 94L, DungeonName = "Plateau de Ush", EntranceMapId = 160960771L, ExitMapId = 162006016L, NpcTemplateId = 3103, NpcName = "Chalfred", QuestionMessageId = 22678, EnterReplyId = 617570, ResumeReplyId = 617923, ExitReplyId = 617986 },
            } },
            { 161742848L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 93L, DungeonName = "Miausolée du Pounicheur", EntranceMapId = 161742848L, ExitMapId = 161744896L, NpcTemplateId = 3097, NpcName = "Caporal Tomonte", QuestionMessageId = 22674, EnterReplyId = 27266, ResumeReplyId = 618580, ExitReplyId = 617618 },
            } },
            { 166985728L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 11L, DungeonName = "Clos des Blops", EntranceMapId = 166985728L, ExitMapId = 166985728L, NpcTemplateId = 1034, NpcName = "Bibiblop", QuestionMessageId = 5402, EnterReplyId = 378713, ResumeReplyId = 659112, ExitReplyId = 660256 },
                new OneAirDungeonResumeEntry { DungeonId = 49L, DungeonName = "Antre du Blop Multicolore Royal", EntranceMapId = 166985728L, ExitMapId = 166985728L, NpcTemplateId = 1034, NpcName = "Bibiblop", QuestionMessageId = 5402, EnterReplyId = 378713, ResumeReplyId = 918032, ExitReplyId = 660256 },
            } },
            { 168560640L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 98L, DungeonName = "Temple de Koutoulou", EntranceMapId = 168560640L, ExitMapId = 168560640L, NpcTemplateId = 3259, NpcName = "Sanazero", QuestionMessageId = 24312, EnterReplyId = 657679, ResumeReplyId = 655857, ExitReplyId = 657653 },
            } },
            { 168820736L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 99L, DungeonName = "Palais de Dantinéa", EntranceMapId = 168820736L, ExitMapId = 168820736L, NpcTemplateId = 3255, NpcName = "Kruchula", QuestionMessageId = 24326, EnterReplyId = 657662, ResumeReplyId = 657651, ExitReplyId = 657680 },
            } },
            { 169084930L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 97L, DungeonName = "Vaisseau du Capitaine Meno", EntranceMapId = 169084930L, ExitMapId = 169084930L, NpcTemplateId = 3256, NpcName = "Nora Nax", QuestionMessageId = 23764, EnterReplyId = 28553, ResumeReplyId = 654173, ExitReplyId = 654057 },
            } },
            { 171706891L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 15L, DungeonName = "Tanière du Meulou", EntranceMapId = 171706891L, ExitMapId = 171706891L, NpcTemplateId = 3947, NpcName = "Lemik Ilmister", QuestionMessageId = 27552, EnterReplyId = 725733, ResumeReplyId = 725729, ExitReplyId = 725728 },
            } },
            { 172493057L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 14L, DungeonName = "Grotte du Bworker", EntranceMapId = 172493057L, ExitMapId = 172493057L, NpcTemplateId = 712, NpcName = "Bworkie", QuestionMessageId = 2960, EnterReplyId = 28151, ResumeReplyId = 727411, ExitReplyId = 28155 },
            } },
            { 173280513L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 100L, DungeonName = "Cimetière des Mastodontes", EntranceMapId = 173280513L, ExitMapId = 173280513L, NpcTemplateId = 3646, NpcName = "Carl Os", QuestionMessageId = 26005, EnterReplyId = 698637, ResumeReplyId = 884983, ExitReplyId = 698479 },
            } },
            { 173540352L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 101L, DungeonName = "Caverne d'El Piko", EntranceMapId = 173540352L, ExitMapId = 173540352L, NpcTemplateId = 3657, NpcName = "Enubie", QuestionMessageId = 26148, EnterReplyId = 700034, ResumeReplyId = 700031, ExitReplyId = 699874 },
            } },
            { 174850048L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 102L, DungeonName = "Boyau du Père Ver", EntranceMapId = 174850048L, ExitMapId = 174850048L, NpcTemplateId = 3679, NpcName = "Goba Fett", QuestionMessageId = 26439, EnterReplyId = 713414, ResumeReplyId = 713418, ExitReplyId = 714121 },
            } },
            { 175637504L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 103L, DungeonName = "Chambre de Tal Kasha", EntranceMapId = 175637504L, ExitMapId = 175637504L, NpcTemplateId = 3686, NpcName = "Drol Novranrac", QuestionMessageId = 26444, EnterReplyId = 714146, ResumeReplyId = 918258, ExitReplyId = 713442 },
            } },
            { 177079296L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 35L, DungeonName = "Laboratoire de Brumen Tinctorias", EntranceMapId = 177079296L, ExitMapId = 177079296L, NpcTemplateId = 1410, NpcName = "Tassa", QuestionMessageId = 8666, EnterReplyId = 380634, ResumeReplyId = 380633, ExitReplyId = 29593 },
            } },
            { 179438082L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 104L, DungeonName = "Camp du Comte Razof", EntranceMapId = 179438082L, ExitMapId = 179438082L, NpcTemplateId = 3747, NpcName = "Dédé", QuestionMessageId = 26892, EnterReplyId = 721757, ResumeReplyId = 721753, ExitReplyId = 721752 },
            } },
            { 179831808L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 106L, DungeonName = "Manoir des Katrepat", EntranceMapId = 179831808L, ExitMapId = 179831808L, NpcTemplateId = 3962, NpcName = "Bozime", QuestionMessageId = 27635, EnterReplyId = 726819, ResumeReplyId = 726815, ExitReplyId = 726814 },
            } },
            { 181146624L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 22L, DungeonName = "Temple du Grand Ougah", EntranceMapId = 181146624L, ExitMapId = 181146624L, NpcTemplateId = 1036, NpcName = "Ernesto Rouste", QuestionMessageId = 5471, EnterReplyId = 27603, ResumeReplyId = 727437, ExitReplyId = 767193 },
            } },
            { 181797888L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 105L, DungeonName = "Chapiteau des Magik Riktus", EntranceMapId = 181797888L, ExitMapId = 181797888L, NpcTemplateId = 3966, NpcName = "Guichetière du Magik Riktus", QuestionMessageId = 27617, EnterReplyId = 726589, ResumeReplyId = 726585, ExitReplyId = 726584 },
            } },
            { 182452224L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 96L, DungeonName = "Temple Maudit d'Araknas", EntranceMapId = 182452224L, ExitMapId = 172757504L, NpcTemplateId = 3212, NpcName = "Disciple d'Araknas", QuestionMessageId = 23442, EnterReplyId = 625876, ResumeReplyId = 626277, ExitReplyId = 626064 },
            } },
            { 183108098L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 109L, DungeonName = "Tour de Solar", EntranceMapId = 183108098L, ExitMapId = 183108098L, NpcTemplateId = 4188, NpcName = "Tourier Calciné", QuestionMessageId = 30308, EnterReplyId = 745450, ResumeReplyId = 745446, ExitReplyId = 745445 },
            } },
            { 183501836L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 107L, DungeonName = "Belvédère d'Ilyzaelle", EntranceMapId = 183501836L, ExitMapId = 183501836L, NpcTemplateId = 4058, NpcName = "Gardien du Jour sans fin", QuestionMessageId = 28770, EnterReplyId = 733094, ResumeReplyId = 733090, ExitReplyId = 733089 },
            } },
            { 185861122L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 32L, DungeonName = "Nid du Kwakwa", EntranceMapId = 185861122L, ExitMapId = 185861122L, NpcTemplateId = 1404, NpcName = "Gentil Organisateur Kwakerbak", QuestionMessageId = 8507, EnterReplyId = 21383, ResumeReplyId = 380966, ExitReplyId = 28718 },
            } },
            { 185861634L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 18L, DungeonName = "Pitons Rocheux des Craqueleurs", EntranceMapId = 185861634L, ExitMapId = 185861634L, NpcTemplateId = 772, NpcName = "Krakotte", QuestionMessageId = 3162, EnterReplyId = 378765, ResumeReplyId = 767076, ExitReplyId = 24303 },
            } },
            { 186384896L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 108L, DungeonName = "Tour de Bethel", EntranceMapId = 186384896L, ExitMapId = 186384896L, NpcTemplateId = 4189, NpcName = "Tourier Submergé", QuestionMessageId = 30312, EnterReplyId = 745483, ResumeReplyId = 745479, ExitReplyId = 745478 },
            } },
            { 190056961L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 19L, DungeonName = "Château Ensablé", EntranceMapId = 190056961L, ExitMapId = 190056961L, NpcTemplateId = 798, NpcName = "Capitaine Igloute", QuestionMessageId = 3281, EnterReplyId = 378772, ResumeReplyId = 751377, ExitReplyId = 24657 },
            } },
            { 194779138L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 110L, DungeonName = "Brasserie du roi Dazak", EntranceMapId = 194779138L, ExitMapId = 194779138L, NpcTemplateId = 4499, NpcName = "Triboulette", QuestionMessageId = 31789, EnterReplyId = 759645, ResumeReplyId = 759641, ExitReplyId = 759640 },
            } },
            { 196346371L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 113L, DungeonName = "Fonderie des Waddicts", EntranceMapId = 196346371L, ExitMapId = 196346371L, NpcTemplateId = 4819, NpcName = "Contwemaîtwe Mihop", QuestionMessageId = 33781, EnterReplyId = 789758, ResumeReplyId = 789769, ExitReplyId = 789762 },
            } },
            { 197133314L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 111L, DungeonName = "Temple du dieu Kao", EntranceMapId = 197133314L, ExitMapId = 197133314L, NpcTemplateId = 4818, NpcName = "Adorateur de Kao", QuestionMessageId = 33783, EnterReplyId = 789756, ResumeReplyId = 844975, ExitReplyId = 789744 },
            } },
            { 197526528L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 112L, DungeonName = "Croquanterie", EntranceMapId = 197526528L, ExitMapId = 197526528L, NpcTemplateId = 4817, NpcName = "Jeanne Nœud-Os", QuestionMessageId = 33782, EnterReplyId = 789771, ResumeReplyId = 789770, ExitReplyId = 789775 },
            } },
            { 197918722L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 114L, DungeonName = "Sanctuaire de Torkélonia", EntranceMapId = 197918722L, ExitMapId = 197918722L, NpcTemplateId = 4976, NpcName = "Porte-clefs de Torkélonia", QuestionMessageId = 35704, EnterReplyId = 803817, ResumeReplyId = 803813, ExitReplyId = 803812 },
            } },
            { 198967296L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 7L, DungeonName = "Antre de Crocabulia", EntranceMapId = 198967296L, ExitMapId = 86248450L, NpcTemplateId = 789, NpcName = "Ziho", QuestionMessageId = 3236, EnterReplyId = 802811, ResumeReplyId = 802807, ExitReplyId = 802820 },
            } },
            { 201328640L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 117L, DungeonName = "Arbre de Mort", EntranceMapId = 201328640L, ExitMapId = 201328640L, NpcTemplateId = 5367, NpcName = "Rafflesia la Fétide", QuestionMessageId = 39057, EnterReplyId = 820389, ResumeReplyId = 820396, ExitReplyId = 820395 },
            } },
            { 201591809L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 120L, DungeonName = "Trône de Sang", EntranceMapId = 201591809L, ExitMapId = 201591809L, NpcTemplateId = 5325, NpcName = "Kapelache", QuestionMessageId = 39011, EnterReplyId = 819924, ResumeReplyId = 819931, ExitReplyId = 819930 },
            } },
            { 201851392L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 119L, DungeonName = "Sentence de la Balance", EntranceMapId = 201851392L, ExitMapId = 201851392L, NpcTemplateId = 5363, NpcName = "Bree Caule", QuestionMessageId = 39334, EnterReplyId = 822701, ResumeReplyId = 822697, ExitReplyId = 822696 },
            } },
            { 202115584L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 118L, DungeonName = "Fers de la Tyrannie", EntranceMapId = 202115584L, ExitMapId = 202115584L, NpcTemplateId = 5319, NpcName = "Miradar", QuestionMessageId = 38913, EnterReplyId = 818783, ResumeReplyId = 821308, ExitReplyId = 818778 },
            } },
            { 204604416L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 121L, DungeonName = "Tempête de l'Eliocalypse", EntranceMapId = 204604416L, ExitMapId = 204604416L, NpcTemplateId = 5469, NpcName = "Martalo", QuestionMessageId = 39975, EnterReplyId = 827247, ResumeReplyId = 827267, ExitReplyId = 827273 },
            } },
            { 204999425L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 123L, DungeonName = "Vallée de la Dame des eaux", EntranceMapId = 204999425L, ExitMapId = 204999425L, NpcTemplateId = 5683, NpcName = "Kyhuri", QuestionMessageId = 41477, EnterReplyId = 842799, ResumeReplyId = 842795, ExitReplyId = 842794 },
            } },
            { 205260802L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 126L, DungeonName = "Atelier du Tanukouï San", EntranceMapId = 205260802L, ExitMapId = 205260802L, NpcTemplateId = 5733, NpcName = "Tanugu Asuo", QuestionMessageId = 41849, EnterReplyId = 844932, ResumeReplyId = 844939, ExitReplyId = 844927 },
            } },
            { 205521925L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 125L, DungeonName = "Bambusaie de Damadrya", EntranceMapId = 205521925L, ExitMapId = 205521925L, NpcTemplateId = 5601, NpcName = "Vusi", QuestionMessageId = 41280, EnterReplyId = 841901, ResumeReplyId = 841889, ExitReplyId = 841888 },
            } },
            { 206177797L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 124L, DungeonName = "Fabrique de foux d'artifice", EntranceMapId = 206177797L, ExitMapId = 206177797L, NpcTemplateId = 5646, NpcName = "Hinaba", QuestionMessageId = 40895, EnterReplyId = 840469, ResumeReplyId = 842485, ExitReplyId = 840464 },
            } },
            { 206832641L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 132L, DungeonName = "Tombe du Shogun Tofugawa", EntranceMapId = 206832641L, ExitMapId = 206832641L, NpcTemplateId = 5829, NpcName = "Yinchika", QuestionMessageId = 42762, EnterReplyId = 854809, ResumeReplyId = 854805, ExitReplyId = 854804 },
            } },
            { 207095299L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 131L, DungeonName = "Demeure des Esprits", EntranceMapId = 207095299L, ExitMapId = 207095299L, NpcTemplateId = 5831, NpcName = "Jibakurei", QuestionMessageId = 42988, EnterReplyId = 855813, ResumeReplyId = 855809, ExitReplyId = 855808 },
            } },
            { 209191685L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 122L, DungeonName = "Dojo du Vent", EntranceMapId = 209191685L, ExitMapId = 209191685L, NpcTemplateId = 5734, NpcName = "Deshi", QuestionMessageId = 41845, EnterReplyId = 844912, ResumeReplyId = 856656, ExitReplyId = 844907 },
            } },
            { 210633732L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 133L, DungeonName = "Mémoire d'Orukam", EntranceMapId = 210633732L, ExitMapId = 211552256L, NpcTemplateId = 6020, NpcName = "Kagikam", QuestionMessageId = 43961, EnterReplyId = 877794, ResumeReplyId = 877790, ExitReplyId = 57811 },
            } },
            { 210765572L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 134L, DungeonName = "Souvenir d'Imagiro", EntranceMapId = 210765572L, ExitMapId = 211552256L, NpcTemplateId = 6021, NpcName = "Imakagi", QuestionMessageId = 43960, EnterReplyId = 877802, ResumeReplyId = 877798, ExitReplyId = 877797 },
            } },
            { 214961664L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 135L, DungeonName = "Rituel de Kabahal", EntranceMapId = 214961664L, ExitMapId = 214961664L, NpcTemplateId = 6214, NpcName = "Na'Hama", QuestionMessageId = 46457, EnterReplyId = 900660, ResumeReplyId = 900849, ExitReplyId = 900655 },
            } },
            { 216927751L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 43L, DungeonName = "Sousouricière du Rat Noir", EntranceMapId = 216927751L, ExitMapId = 218894338L, NpcTemplateId = 800, NpcName = "Rat Pido", QuestionMessageId = 3294, EnterReplyId = 379729, ResumeReplyId = 924247, ExitReplyId = 767152 },
            } },
            { 219939328L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 136L, DungeonName = "Bataille de l'Aurore Pourpre", EntranceMapId = 219939328L, ExitMapId = 219939328L, NpcTemplateId = 6381, NpcName = "Horreur de l'Aurore", QuestionMessageId = 49299, EnterReplyId = 920834, ResumeReplyId = 920830, ExitReplyId = 920829 },
            } },
            { 221250562L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 139L, DungeonName = "Tertre du long sommeil", EntranceMapId = 221250562L, ExitMapId = 221250562L, NpcTemplateId = 2217, NpcName = "Hell Mina", QuestionMessageId = 16750, EnterReplyId = 938105, ResumeReplyId = 937494, ExitReplyId = 937376 },
            } },
            { 223350028L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 142L, DungeonName = "Refuge sylvestre", EntranceMapId = 223350028L, ExitMapId = 224137218L, NpcTemplateId = 6809, NpcName = "Don El Wolfo", QuestionMessageId = 51487, EnterReplyId = 972314, ResumeReplyId = 972310, ExitReplyId = 972309 },
            } },
            { 224660233L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 140L, DungeonName = "Chambre des maléfices", EntranceMapId = 224660233L, ExitMapId = 223875074L, NpcTemplateId = 6929, NpcName = "Bulbybell", QuestionMessageId = 51845, EnterReplyId = 981915, ResumeReplyId = 981942, ExitReplyId = 981919 },
            } },
            { 225313792L, new List<OneAirDungeonResumeEntry> {
                new OneAirDungeonResumeEntry { DungeonId = 141L, DungeonName = "Bastion des Marteaux-Aigris", EntranceMapId = 225313792L, ExitMapId = 225185794L, NpcTemplateId = 6848, NpcName = "Pasmühr Aye", QuestionMessageId = 51545, EnterReplyId = 974323, ResumeReplyId = 977437, ExitReplyId = 974318 },
            } },
        };
    }
}
